version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: learning_platform_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: student_learning_platform
    networks:
      - learning_platform

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: learning_platform_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/student_learning_platform
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - learning_platform

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: learning_platform_ui
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - learning_platform

volumes:
  mongodb_data:

networks:
  learning_platform:
    driver: bridge